In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros([state_space_size, action_space_size])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
rewards_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
            
        #E xploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # max indices of max value in that row
        else:
            action = env.action_space.sample() # sample random action

        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("**********Average reward per thousand episodes**********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-table
print("\n\n**********Q-table**********\n")
print(q_table)

**********Average reward per thousand episodes**********

1000 :  0.03100000000000002
2000 :  0.19800000000000015
3000 :  0.3880000000000003
4000 :  0.5610000000000004
5000 :  0.6290000000000004
6000 :  0.6500000000000005
7000 :  0.6450000000000005
8000 :  0.6860000000000005
9000 :  0.6880000000000005
10000 :  0.6760000000000005


**********Q-table**********

[[0.53549788 0.51465204 0.5250178  0.50405904]
 [0.22506697 0.33568619 0.32181566 0.50044779]
 [0.41693658 0.4018138  0.39998804 0.47292336]
 [0.21587589 0.28366845 0.27916944 0.46007636]
 [0.55304699 0.32170216 0.33291937 0.39129985]
 [0.         0.         0.         0.        ]
 [0.1290762  0.10123169 0.36685849 0.12190382]
 [0.         0.         0.         0.        ]
 [0.38467112 0.49665212 0.44679518 0.58140756]
 [0.41647911 0.62356375 0.36842837 0.42471862]
 [0.55935482 0.31092201 0.35447373 0.32819544]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53337784 0.49569505 0.7